# Include aether dynamic theme
include ~/.config/aether/theme/kitty.conf

# Clipboard & Copy/Paste configuration
map super+c copy_to_clipboard
map super+v paste_from_clipboard
map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary
