[bar]
background = "#1e1e2e"
text = "#cdd6f4"
active = "#cba6f7"
size-horizontal = 30
size-vertical = 30

[popups]
background = "#181825"
text = "#cdd6f4"
border = "#313244"

[tooltip]
background = "#11111b"
text = "#cdd6f4"
border = "#45475a"

[notifications]
background = "#181825"
text = "#cdd6f4"
border = "#cba6f7"
countdown = "#cba6f7"

[menu]
background = "#181825"
text = "#cdd6f4"
border = "#313244"
selected-background = "#313244"
selected-text = "#cba6f7"

[controls]
normal-fill-alpha = 0.08
hover-cursor-fill-alpha = 0.15
selected-fill-alpha = 0.25
